#!/bin/bash
cd service_config/
docker build --no-cache --tag configservice .
cd ..

cd service_objectstore/
docker build --no-cache --tag objectservice .
cd ..

cd service_server/
docker build --no-cache --tag serverservice .
cd ..

echo "REMEMBER TO SET ONLINE-MODE IN Communication.js TO true"

read -p "prompt"